### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by anirudh242** [dogegarden/dogehouse.js#36]
I'm using Dogehouse.JS 2.0.2 and when I try to run the example JS code from the README- 
```
const { Client } = require('dogehouse.js');
const app = new Client();
app.connect(process.env.DOGEHOUSE_TOKEN, process.env.DOGEHOUSE_REFRESH_TOKEN).then(async () => {
    console.log('Bot connected!');
    console.log(await app.rooms.top); // Log all of your top rooms to console
});
``` 
I get the error-
```
C:\Users\Dell\Desktop\dogehouse_bot\node_modules\dogehouse.js\src\classes\Chat.js:15
                this._cooldown = options.cooldown ?? defaultChatCooldown;
                                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Dell\Desktop\Coding Projects\Javascript\dogehouse_bot\node_modules\dogehouse.js\src\Client.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by pctfgm** [comment]
What nodejs version r u using?

**Comment by ebarracchia** [comment]
Please add this at the top of your file

require('dotenv').config()

**Comment by HoloPanio** [comment]
Hello,

As mentioned by the previous two users, please add `require('dotenv').config();` to the top of your file, and also please give us your node version so that we can ensure that you are not using an unsupported version of Node.js.  

If you are having trouble require 'dotenv', please try installing the repository by running `npm i dotenv` in your terminal.

**Comment by dhenson02** [comment]
You need Node >= 14 @anirudh242
